### ISSUE TITLE
aes encode and decode

### ISSUE THREAD

**Issue by culiangfanzi** [polaris1119/myblog_article_code#1]
I have tryied your source code to encrypt  in php and go using aes , but I got different encrypted string ..Do you hava any advise for me to solve this problem ?

here is my php code：
    public function encode($mode=MCRYPT_MODE_CBC)
    {
        $td;
        switch($mode)
        {
            case MCRYPT_MODE_CFB:
                $td=mcrypt_module_open(MCRYPT_RIJNDAEL_128,'',MCRYPT_MODE_CFB,'');
                break;
            case MCRYPT_MODE_ECB:
                $td=mcrypt_module_open(MCRYPT_RIJNDAEL_128,'',MCRYPT_MODE_ECB,'');
                break;
             case MCRYPT_MODE_CBC:
                $td=mcrypt_module_open(MCRYPT_RIJNDAEL_128,'',MCRYPT_MODE_CBC,'');
                break;
        }
        //$iv=  mb_substr($data,0,16,'ascii');
        if(mcrypt_generic_init($td, $this->secretKey, $this->iv)==-1)
        {
            trigger_error("mcrypt_generic_init error".Json::encode($td),E_USER_ERROR);
            return;
        }

```
    $blockSize=mcrypt_enc_get_block_size($td);
    $data=$this->pkcs5padding($this->encryptData, $blockSize);
    $cryptedData=  mcrypt_generic($td, $data);
    //$cryptedData= mcrypt_encrypt(MCRYPT_RIJNDAEL_128,$this->secretKey, $this->encryptData, MCRYPT_MODE_CFB,$this->iv);
    //mcrypt_generic_deinit($td);
    //mcrypt_module_close($td);
    return base64_encode($cryptedData);
}
```

**Comment by polaris1119** [comment]
pkcs5padding 和我代码一致吗？在我代码基础上修改试试呢？

**Comment by culiangfanzi** [comment]
一致了，ok了。被php和go加密的不一致坑了半天
