### ISSUE TITLE
请问有没有PKCS7的加解密

### ISSUE THREAD

**Issue by sinmaystar** [polaris1119/myblog_article_code#2]
博主您好，我想用go和oc做aes加解密，但是oc只支持pkcs7的方式，请问我在一篇比较久远的网页中看到您和其他人探讨过（http://bbs.studygolang.com/thread-25-1-1.html）
请问，有pkcs7的代码吗？上述网页里面的代码下载链接已经失效。
感谢博主的帮忙

**Comment by polaris1119** [comment]
http://dwz.cn/3XjA30
